apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry-pv
  namespace: registry
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.26
    path: "/NFS/k8s-docker-registry"